import { IForecast, DegreeType } from './forecast.models';

export const forecastData: IForecast[] = [
  {
    day: 'Monday',
    desciption: 'Rainy',
    degreeType: DegreeType.Celsius,
    icon: 'info',
    image: 'assets/img/icons/10.svg',
    min: 13,
    max: 24,
    details: {
      chanceForRain: 62,
      isOpened: false,
      sunrise: '5:12',
      windSpeed: 8,
    },
  },
  {
    day: 'Tuesday',
    desciption: 'Thunderstorm',
    degreeType: DegreeType.Celsius,
    icon: 'info',
    image: 'assets/img/icons/22.svg',
    min: 13,
    max: 21,
    details: {
      chanceForRain: 74,
      isOpened: false,
      sunrise: '5:13',
      windSpeed: 6,
    },
  },
  {
    day: 'Wednesday',
    desciption: 'Rain',
    degreeType: DegreeType.Celsius,
    icon: 'info',
    image: 'assets/img/icons/9.svg',
    min: 13,
    max: 22,
    details: {
      chanceForRain: 55,
      isOpened: false,
      sunrise: '5:09',
      windSpeed: 11,
    },
  },
  {
    day: 'Thursday',
    desciption: 'Thunderstorm',
    degreeType: DegreeType.Celsius,
    icon: 'info',
    image: 'assets/img/icons/5.svg',
    min: 13,
    max: 24,
    details: {
      chanceForRain: 59,
      isOpened: false,
      sunrise: '5:17',
      windSpeed: 10,
    },
  },
  {
    day: 'Friday',
    desciption: 'Cloudy',
    degreeType: DegreeType.Celsius,
    icon: 'info',
    image: 'assets/img/icons/4.svg',
    min: 13,
    max: 20,
    details: {
      chanceForRain: 47,
      isOpened: false,
      sunrise: '5:11',
      windSpeed: 18,
    },
  },
  {
    day: 'Saturday',
    desciption: 'Sunny',
    degreeType: DegreeType.Celsius,
    icon: 'info',
    image: 'assets/img/icons/2.svg',
    min: 15,
    max: 21,
    details: {
      chanceForRain: 23,
      isOpened: false,
      sunrise: '5:14',
      windSpeed: 8,
    },
  },
  {
    day: 'Sunday',
    desciption: 'Hot',
    degreeType: DegreeType.Celsius,
    icon: 'info',
    image: 'assets/img/icons/1.svg',
    min: 16,
    max: 26,
    details: {
      chanceForRain: 12,
      isOpened: false,
      sunrise: '5:18',
      windSpeed: 14,
    },
  },

];
